name: 'Continuous Deployment'

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

env:
  DOTNET_VERSION: '9.0.x'

jobs:
  build-and-deploy-dev:
    environment: Development
    runs-on: ubuntu-latest

    env:
      AZURE_CLIENT_ID: ${{ vars.AZURE_CLIENT_ID }}
      AZURE_TENANT_ID: ${{ vars.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ vars.AZURE_SUBSCRIPTION_ID }}
      AZURE_LOCATION: "uksouth"
      AZURE_ENV_NAME: "dev"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install azd
        run: |
          curl -fsSL https://aka.ms/install-azd.sh | bash
          echo "$HOME/.azd/bin" >> $GITHUB_PATH

      - name: Log in with Azure (Federated Credentials)
        run: |
          azd auth login \
            --client-id "$AZURE_CLIENT_ID" \
            --federated-credential-provider "github" \
            --tenant-id "$AZURE_TENANT_ID"

      - name: Provision Infrastructure
        run: azd provision --no-prompt

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Deploy Application
        run: azd deploy --no-prompt

  ui-test-dev:
    environment: Development
    runs-on: ubuntu-latest

    needs: [build-and-deploy-dev]

    env:
      AZURE_CLIENT_ID: ${{ vars.AZURE_CLIENT_ID }}
      AZURE_TENANT_ID: ${{ vars.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ vars.AZURE_SUBSCRIPTION_ID }}
      AZURE_ENV_NAME: "dev"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install azd
        run: |
          curl -fsSL https://aka.ms/install-azd.sh | bash
          echo "$HOME/.azd/bin" >> $GITHUB_PATH

      - name: Log in with Azure (Federated Credentials)
        run: |
          azd auth login \
            --client-id "$AZURE_CLIENT_ID" \
            --federated-credential-provider "github" \
            --tenant-id "$AZURE_TENANT_ID"

      - name: Get deployed web app URL
        id: get-url
        run: |
          webAppUrl=$(azd show --output json | jq -r '.services.web.endpoint')
          echo "WEB_APP_URL=$webAppUrl" >> $GITHUB_OUTPUT

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Build UI Tests Project
        run: dotnet build src/MX.Skilling.Web.UITests --configuration Release

      - name: Install Playwright Browsers
        run: pwsh src/MX.Skilling.Web.UITests/bin/Release/net9.0/playwright.ps1 install chromium firefox webkit

      - name: Run UI Tests
        env:
          WEB_APP_URL: ${{ steps.get-url.outputs.WEB_APP_URL }}
        run: dotnet test src/MX.Skilling.Web.UITests --configuration Release --no-build --verbosity normal

  build-and-deploy-prd:
    environment: Production
    runs-on: ubuntu-latest

    needs: [ui-test-dev]

    env:
      AZURE_CLIENT_ID: ${{ vars.AZURE_CLIENT_ID }}
      AZURE_TENANT_ID: ${{ vars.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ vars.AZURE_SUBSCRIPTION_ID }}
      AZURE_LOCATION: "uksouth"
      AZURE_ENV_NAME: "prd"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install azd
        run: |
          curl -fsSL https://aka.ms/install-azd.sh | bash
          echo "$HOME/.azd/bin" >> $GITHUB_PATH

      - name: Log in with Azure (Federated Credentials)
        run: |
          azd auth login \
            --client-id "$AZURE_CLIENT_ID" \
            --federated-credential-provider "github" \
            --tenant-id "$AZURE_TENANT_ID"

      - name: Provision Infrastructure
        run: azd provision --no-prompt

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Deploy Application
        run: azd deploy --no-prompt

  ui-test-prd:
    environment: Production
    runs-on: ubuntu-latest

    needs: [build-and-deploy-prd]

    env:
      AZURE_CLIENT_ID: ${{ vars.AZURE_CLIENT_ID }}
      AZURE_TENANT_ID: ${{ vars.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ vars.AZURE_SUBSCRIPTION_ID }}
      AZURE_ENV_NAME: "prd"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install azd
        run: |
          curl -fsSL https://aka.ms/install-azd.sh | bash
          echo "$HOME/.azd/bin" >> $GITHUB_PATH

      - name: Log in with Azure (Federated Credentials)
        run: |
          azd auth login \
            --client-id "$AZURE_CLIENT_ID" \
            --federated-credential-provider "github" \
            --tenant-id "$AZURE_TENANT_ID"

      - name: Get deployed web app URL
        id: get-url
        run: |
          webAppUrl=$(azd show --output json | jq -r '.services.web.endpoint')
          echo "WEB_APP_URL=$webAppUrl" >> $GITHUB_OUTPUT

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Build UI Tests Project
        run: dotnet build src/MX.Skilling.Web.UITests --configuration Release

      - name: Install Playwright Browsers
        run: pwsh src/MX.Skilling.Web.UITests/bin/Release/net9.0/playwright.ps1 install chromium firefox webkit

      - name: Run UI Tests
        env:
          WEB_APP_URL: ${{ steps.get-url.outputs.WEB_APP_URL }}
        run: dotnet test src/MX.Skilling.Web.UITests --configuration Release --no-build --verbosity normal
